### ISSUE TITLE
ShowcaseTwitter Styling

### ISSUE THREAD

**Issue by awhitford** [HiDeoo/starlight-showcases#7]
### Is your feature request related to a problem?

I wasn't happy with the styling of this X/Twitter post:
```mdx
<ShowcaseTwitter
  entries={[
    'https://x.com/StartupArchive_/status/1829849129121628267',
  ]}
/>
```

However, once I added this:
```mdx
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
```
then I was happy with the styling because it showed the embedded video.

### Describe the solution you'd like

It would be great if this extra script was automatically included?

### Describe alternatives you've considered

At the very least, adding the script could be added to the documentation.

**Comment by HiDeoo** [comment]
Thanks for your feedback :raised_hands:

The minimal widget with zero JavaScript loaded by default is indeed by design. I've updated the documentation to clarify this behavior and link to the appropriate resources on how to load the full widget.
