### ISSUE TITLE
ShowcaseImage (and probably more) are broken when using starlight-blog plugin

### ISSUE THREAD

**Issue by stavros-k** [HiDeoo/starlight-showcases#9]
### Describe the bug

<img width="1216" alt="image" src="https://github.com/user-attachments/assets/b7876cde-97ed-4546-83d7-43778c4b99f8">

### To Reproduce

1. Install starlight blog
2. Use ShowcaseImage
3. See result

### Expected behavior

ShowcaseImage display as the demo

### How often does this bug happen?

Every time

**Comment by stavros-k** [comment]
Without blog plugin


<img width="1216" alt="image" src="https://github.com/user-attachments/assets/3cf078de-7a5e-465d-832a-6f727e0a677a">

**Comment by HiDeoo** [comment]
Thanks for the report 🙌 

From my quick tests:

- In dev, some component scoped CSS is randomly missing, restarting the dev server can fix or not.
- In prod, everything works as expected.

At first glance, this looks like an upstream issue that seems to be resolved in Astro 5. I'll test again when Astro 5 stable is released next week.

**Comment by HiDeoo** [comment]
Just tested with the latest version of Astro, Starlight, `starlight-blog` and `starlight-showcases` and I can confirm that the issue is now fixed. Sorry for the inconvenience.
